### ISSUE TITLE
Not works with Alfred 4

### ISSUE THREAD

**Issue by fedor1991** [jaroslawhartman/TimeZones-Alfred#19]
The path for workflow was changed, but here is hardcoded for Alfred 3.

**Comment by jaroslawhartman** [comment]
Hi Vlad, can you give an example?

Thank you,
Jarek

**Comment by fedor1991** [comment]
Oh, sorry, I didn't say that today Alfred 4 was released and workflows have another path

**Comment by fedor1991** [comment]
Okay, now it works. Strange.

**Comment by fedor1991** [comment]
Alfred 4 just released and these vars not actual 
`TZWD="$HOME/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/carlosnz.timezones"
TZPREFS="$HOME/Library/Application Support/Alfred 3/Workflow Data/carlosnz.timezones"`

**Comment by jaroslawhartman** [comment]
Check v2.7 please. 

Closing this ticket for now, will reopen if needed.

Thank you,
Jarek

**Comment by Amparose** [comment]
timezone edit still refers to `~/Library/Application Support/Alfred 3/Workflow Data/carlosnz.timezones/timezones.txt`

Also, timezone move does move the file but then doesn't refer to it and cities go back to default.

**Comment by jaroslawhartman** [comment]
Hi @Amparose 

Well spotted, fixed in v2.9

**Comment by Amparose** [comment]
Hey @jaroslawhartman, the edit file command now works but moving the file (via the command) still doesn't make it read from that file location, which I'm pretty sure the previous version did.

**Comment by jaroslawhartman** [comment]
Hi,

Created a new ticket for this, see #23 .

Best regards,
Jarek
